name: Build Chrome Extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Package extension
        run: |
          mv dist mnemosyne
          zip -r mnemosyne.zip mnemosyne

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: mnemosyne.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
